target-version = "py311"
line-length = 100

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[lint]
select = ["E", "W", "F", "I", "N", "UP", "RUF", "B"]
ignore = []

[lint.per-file-ignores]
"tests/**" = ["RUF"]
