from typing import Protocol

from netbox_vsphere_sync.domain.model.vsphere import (
    Cluster,
    Datastore,
    HostSystem,
    Interface,
    IpAddress,
    PortGroup,
    Site,
    Vlan,
)


class SiteRepository(Protocol):
    def list_all(self) -> list[Site]: ...
    def find_by_name(self, name: str) -> Site | None: ...
    def create(self, site: Site) -> Site: ...
    def update(self, site: Site) -> Site: ...
    def delete(self, netbox_id: int) -> bool: ...


class ClusterRepository(Protocol):
    def list_all(self) -> list[Cluster]: ...
    def find_by_natural_key(self, site: str, name: str) -> Cluster | None: ...
    def create(self, cluster: Cluster) -> Cluster: ...
    def update(self, cluster: Cluster) -> Cluster: ...
    def delete(self, netbox_id: int) -> bool: ...


class DeviceRepository(Protocol):
    def list_all(self) -> list[HostSystem]: ...
    def find_by_natural_key(self, site: str, name: str) -> HostSystem | None: ...
    def create(self, device: HostSystem) -> HostSystem: ...
    def update(self, device: HostSystem) -> HostSystem: ...
    def delete(self, netbox_id: int) -> bool: ...


class InterfaceRepository(Protocol):
    def list_all(self) -> list[Interface]: ...
    def find_by_natural_key(self, device: str, name: str) -> Interface | None: ...
    def create(self, interface: Interface) -> Interface: ...
    def update(self, interface: Interface) -> Interface: ...
    def delete(self, netbox_id: int) -> bool: ...


class IpAddressRepository(Protocol):
    def list_all(self) -> list[IpAddress]: ...
    def find_by_natural_key(
        self, address: str, device: str, interface: str
    ) -> IpAddress | None: ...
    def create(self, ip_address: IpAddress) -> IpAddress: ...
    def update(self, ip_address: IpAddress) -> IpAddress: ...
    def delete(self, netbox_id: int) -> bool: ...


class VlanRepository(Protocol):
    def list_all(self) -> list[Vlan]: ...
    def find_by_natural_key(self, site: str, vid: int) -> Vlan | None: ...
    def create(self, vlan: Vlan) -> Vlan: ...
    def update(self, vlan: Vlan) -> Vlan: ...
    def delete(self, netbox_id: int) -> bool: ...


class InventoryItemRepository(Protocol):
    def list_all(self) -> list[Datastore]: ...
    def find_by_natural_key(self, device: str, name: str, role: str) -> Datastore | None: ...
    def create(self, item: Datastore) -> Datastore: ...
    def update(self, item: Datastore) -> Datastore: ...
    def delete(self, netbox_id: int) -> bool: ...


class VSphereCollector(Protocol):
    def collect_sites(self) -> list[Site]: ...
    def collect_clusters(self) -> list[Cluster]: ...
    def collect_hosts(self) -> list[HostSystem]: ...
    def collect_port_groups(self) -> list[PortGroup]: ...
    def collect_datastores(self) -> list[Datastore]: ...


class NetBoxBootstrap(Protocol):
    def ensure_manufacturer(self, name: str) -> None: ...
    def ensure_device_role(self, name: str, color: str) -> None: ...
    def ensure_cluster_type(self, name: str) -> None: ...
    def ensure_custom_fields(self) -> None: ...


class LockManager(Protocol):
    def acquire(self) -> bool: ...
    def release(self) -> None: ...
    def is_locked(self) -> bool: ...
